# Generated by Django 2.2.17 on 2021-01-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210114_1220'),
        ('authapp', '0005_auto_20210117_1940'),
    ]

    operations = [
    ]
