# Generated by Django 3.1.6 on 2021-02-11 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_auto_20210211_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 15, 4, 50, 784646, tzinfo=utc)),
        ),
    ]
