# Generated by Django 2.2.17 on 2020-12-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryEditForm',
            fields=[
                ('productcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.ProductCategory')),
            ],
            bases=('mainapp.productcategory',),
        ),
    ]
