# Generated by Django 2.2.17 on 2021-01-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategoryEditForm',
        ),
    ]
